project:
  type: website

website:
  title: "Maik Bieleke"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: About
      - text: Publications
        href: publications/index.qmd
      - text: Questionnaires
        href: publications/bieleke-barton-wolff-2021-cognition-emotion/index.qmd

  page-footer:  
    left: >-
     &#169; 2023 Maik Bieleke &#8729; Made with [Quarto](https://quarto.org)
     
    center: |
      <a class="link-dark me-1" href="https://twitter.com/MBieleke" title="Twitter" target="_blank" rel="noopener">{{< fa brands twitter >}}</a>
      <a class="link-dark me-1" href="https://github.com/MBieleke/" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0003-2586-1416" title="Orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.de/citations?user=EbGUz_gAAAAJ&hl=en" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="https://www.linkedin.com/in/maik-bieleke/" title="Linkedin" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

